FROM webhippie/alpine:latest-amd64@sha256:4c910b2b8e5785d9ea09325b84b47543dc2674813f392313952e515ea2dd9a99

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Golang" \
  org.opencontainers.image.vendor="Thomas Boerger"

WORKDIR /srv/app

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:/usr/local/go/bin:${PATH}
ENV GO111MODULE auto

COPY ./overlay ./overlay-amd64 /

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial go protoc protobuf-dev binutils-gold && \
  export GOROOT_BOOTSTRAP="$(go env GOROOT)" && \
  export GOOS="$(go env GOOS)" && \
  export GOARCH="$(go env GOARCH)" && \
  export GOHOSTOS="$(go env GOHOSTOS)" && \
  export GOHOSTARCH="$(go env GOHOSTARCH)" && \
  curl -sLo - https://golang.org/dl/go1.14.13.src.tar.gz | tar -xzf - -C /usr/local && \
  cd /usr/local/go/src && \
  bash make.bash && \
  rm -rf /usr/local/go/pkg/bootstrap /usr/local/go/pkg/obj && \
  apk del go && \
  rm -rf /var/cache/apk/*
