FROM webhippie/alpine:latest-arm64v8@sha256:2af125d3829f11d05c99396f5a29d5592f6d44fb37d9c384497fdd7beef62c5b

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Golang" \
  org.label-schema.vcs-url="https://github.com/dockhippie/golang.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:/usr/local/go/bin:${PATH}

COPY ./overlay ./overlay-arm64v8 /

RUN apk update && \
  apk upgrade && \
  apk add build-base git git-lfs mercurial bzr go && \
  export GOROOT_BOOTSTRAP="$(go env GOROOT)" && \
  curl -sLo - https://golang.org/dl/go1.6.4.src.tar.gz | tar -xzf - -C /usr/local && \
  cd /usr/local/go/src && \
  patch -p2 -i /tmp/no-pic.patch && \
  bash make.bash && \
  apk del go && \
  rm -rf /var/cache/apk/*
