FROM webhippie/alpine:latest@sha256:9e1997e04f7fa611f8c114b66ef5c23c7624f890522c1420c3a7f06ddf7ca294

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Golang" \
  org.label-schema.vcs-url="https://github.com/dockhippie/golang.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:/usr/local/go/bin:${PATH}

COPY ./overlay ./overlay-amd64 /

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial bzr go && \
  export GOROOT_BOOTSTRAP="$(go env GOROOT)" && \
  export GOOS="$(go env GOOS)" && \
  export GOARCH="$(go env GOARCH)" && \
  export GOHOSTOS="$(go env GOHOSTOS)" && \
  export GOHOSTARCH="$(go env GOHOSTARCH)" && \
  curl -sLo - https://golang.org/dl/go1.7.6.src.tar.gz | tar -xzf - -C /usr/local && \
  cd /usr/local/go/src && \
  bash make.bash && \
  rm -rf /usr/local/go/pkg/bootstrap /usr/local/go/pkg/obj && \
  apk del go && \
  rm -rf /var/cache/apk/*
