FROM webhippie/alpine:latest@sha256:b59b1749b74862ba4ded8e3890157ea85c071a632b9a5d1166b3058632b1603c

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Golang" \
  org.label-schema.vcs-url="https://github.com/dockhippie/golang.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:/usr/local/go/bin:${PATH}
ENV GO111MODULE auto

COPY ./overlay ./overlay-amd64 /

RUN apk update && \
  apk upgrade && \
  apk add build-base git git-lfs mercurial bzr go && \
  export GOROOT_BOOTSTRAP="$(go env GOROOT)" && \
  curl -sLo - https://golang.org/dl/go1.11.5.src.tar.gz | tar -xzf - -C /usr/local && \
  cd /usr/local/go/src && \
  patch -p2 -i /tmp/default-buildmode-pie.patch && \
  patch -p2 -i /tmp/set-external-linker.patch && \
  bash make.bash && \
  apk del go && \
  rm -rf /var/cache/apk/*
