FROM webhippie/alpine:latest-arm32v6@sha256:f52146000ae31a8e6df968e3ab3680f5d799b1e5cb2100fa90ec71584068b0a7

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Golang" \
  org.label-schema.vcs-url="https://github.com/dockhippie/golang.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

RUN apk update && \
  apk upgrade && \
  apk add build-base git git-lfs mercurial bzr go openssh-client && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
