FROM webhippie/alpine:latest-arm64v8@sha256:47921c78e4cb3dafe1338629eea137dd909882fb01e2583750e110ae4bdcc20b

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Golang" \
  org.label-schema.vcs-url="https://github.com/dockhippie/golang.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

RUN apk update && \
  apk upgrade && \
  apk add build-base git git-lfs mercurial bzr go openssh-client && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm64v8 /
