FROM webhippie/alpine:latest-arm32v6@sha256:8a3ad90c8e7f32729666dbbfe08b4d6a4fc1ddd09d5e908248630a501008c7c0

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Golang" \
  org.opencontainers.image.vendor="Thomas Boerger"

WORKDIR /srv/app

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial go protoc protobuf-dev binutils-gold && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
