FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:a3d2b263aebefdd2e8abda1ff0932ed9c52b07f0456367f02fccdbfdc6cf7a81

WORKDIR /srv/app

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

# renovate: datasource=github-releases depName=upx/upx
ENV UPX_VERSION=4.2.4

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial go protoc protobuf-dev binutils-gold && \
  curl -sSLo- https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-amd64_linux.tar.xz | tar -xJv --strip 1 -C /tmp && \
  mv /tmp/upx /usr/bin/upx && \
  rm -rf /var/cache/apk/* /tmp/*

COPY ./overlay /
