FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:5eab89a3e92fb3fc34402d549e5980ab66fb84b1e2267deb2f7ab593e68fc003

WORKDIR /srv/app

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

# renovate: datasource=github-releases depName=upx/upx
ENV UPX_VERSION=3.96

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial go protoc protobuf-dev binutils-gold && \
  curl -sSLo- https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-arm_linux.tar.xz | tar -xJv --strip 1 -C /tmp && \
  mv /tmp/upx /usr/bin/upx && \
  rm -rf /var/cache/apk/* /tmp/*

COPY ./overlay /
