FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:93493def75ab3695096b69762ca1afe1be11651bad4734e5608a9647e0a55fe1

WORKDIR /srv/app

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

# renovate: datasource=github-releases depName=upx/upx
ENV UPX_VERSION=5.0.2

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial go protoc protobuf-dev binutils-gold && \
  curl -sSLo- https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-amd64_linux.tar.xz | tar -xJv --strip 1 -C /tmp && \
  mv /tmp/upx /usr/bin/upx && \
  rm -rf /var/cache/apk/* /tmp/*

COPY ./overlay /
