FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:5ef1665b9d7d104f93ca110f2e7ceb8677c1a4980b79f02a5ff9476cf2540864

WORKDIR /srv/app

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

# renovate: datasource=github-releases depName=upx/upx
ENV UPX_VERSION=3.96

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial go protoc protobuf-dev binutils-gold && \
  curl -sSLo- https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-arm64_linux.tar.xz | tar -xJv --strip 1 -C /tmp && \
  mv /tmp/upx /usr/bin/upx && \
  rm -rf /var/cache/apk/* /tmp/*

COPY ./overlay /
