FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:ff48ca624b292abcf0862840b216f1f209ee0bc361725b642bca2c467ee2f467

WORKDIR /srv/app

ENV GOPATH /srv/app
ENV PATH /srv/app/bin:${PATH}
ENV GO111MODULE auto

# renovate: datasource=github-releases depName=upx/upx
ENV UPX_VERSION=4.1.0

RUN apk update && \
  apk upgrade && \
  apk add gcc musl-dev openssl openssh-client make git git-lfs mercurial go protoc protobuf-dev binutils-gold && \
  curl -sSLo- https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-arm_linux.tar.xz | tar -xJv --strip 1 -C /tmp && \
  mv /tmp/upx /usr/bin/upx && \
  rm -rf /var/cache/apk/* /tmp/*

COPY ./overlay /
